# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_users:
            entity: { class: AppBundle\Entity\Vendedor, property: nombre }
        in_memory:
            memory: ~

    access_control:
        - { path: ^/clientes, roles: ROLE_USER }
        - { path: ^/api, roles: ROLE_USER }
        - { path: ^/presupuestos, roles: ROLE_USER }


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            guard:
                authenticators:
                    - app.security.login_form_authenticator
            logout:
                path: /logout
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html